# Generated by Django 5.0.7 on 2024-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('date_of_joining', models.DateTimeField()),
                ('status', models.CharField(choices=[('Onboarded', 'Onboarded'), ('Not Onboarded', 'Not Onboarded')], max_length=45)),
                ('project_domain', models.CharField(max_length=25)),
            ],
        ),
    ]
